name: Test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Code
      uses: tomtomecek/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm cit --no-progress --no-audit
